export const base_url_img= "https://image.tmdb.org/t/p/original"
export const todasLasPeliculas = "movie?"
export const base_url = "https://api.themoviedb.org/3/discover/"
export const api_key = "f99c23308f40c1c01f9f6b78ac66fa01"
export const query = "&with_genres=28"
